# Generated by Django 5.0.6 on 2024-06-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidder',
            name='bidder_id',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_id',
        ),
    ]
