# Generated by Django 5.0.6 on 2024-06-11 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_bidder_bidder_id_remove_owner_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.owner'),
        ),
    ]
