# Generated by Django 5.0.6 on 2024-06-11 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_owner_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.owner'),
        ),
    ]
