# Generated by Django 5.0.6 on 2024-06-11 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_owner_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodeuct_category',
            new_name='product_category',
        ),
    ]
