# Generated by Django 5.0.6 on 2024-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_bio_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bio',
            name='token',
        ),
        migrations.AddField(
            model_name='bio',
            name='email_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
